version: '3.8'

services:
  # Development version with hot reload
  api-dev:
    build: .
    container_name: summarizer-api-dev
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.1:8b
      - OLLAMA_TIMEOUT=30
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - LOG_LEVEL=DEBUG
    volumes:
      - ./app:/app/app:ro
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - ollama
    restart: unless-stopped

  # Ollama service (same as production)
  ollama:
    image: ollama/ollama:latest
    container_name: summarizer-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_data_dev:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data_dev:
    driver: local
